global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka_container:9092']

  - job_name: 'zookeeper'
    static_configs:
      - targets: ['zookeeper_container:2181']

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysqld_exporter:9104']

  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb_exporter:9216']

  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres_exporter:9187']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
