global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'host.docker.internal:8081' ]
        labels:
          application: 'notification-service'
